//! Golden-fixture snapshots against real `un*` renderer output.
//!
//! `tests/golden/*.md` are markdown samples generated by running the actual
//! `unpdf`/`undoc`/`unhwp` CLIs against a sample document -- not synthetic
//! input like the property-test generators. `tests/golden/*.refined.md` is
//! the checked-in expected output of `refine()` on that sample: a change to
//! *any* pass that alters what real renderer output looks like after
//! refinement shows up as a diff on the checked-in snapshot file in the
//! commit that caused it, which is what makes the change reviewable (the
//! design doc calls this "before/after diff, reviewed by a human; snapshot
//! updates are reviewed"). This is a different kind of check than
//! `roundtrip_properties.rs`: that harness proves the two invariants hold
//! over *generated* shapes; this one pins *specific* real-world shapes so a
//! future behavior change is visible, not just invariant-checked.
//!
//! Every fixture is also checked directly against both invariants here,
//! independent of the snapshot -- a real sample is exactly the kind of
//! input a passing property-test run could still miss (the generators are
//! deliberately narrow; see `roundtrip_properties.rs`'s own doc comment).

use std::collections::HashSet;
use std::fs;
use std::path::PathBuf;
use unparser_shared::refine::{refine, RefineOptions};

/// Same word-splitting yardstick as `roundtrip_properties.rs` (including
/// the backslash-escape collapse and the `{}` split, both explained there)
/// -- kept as a separate small copy rather than a shared `dev-dependencies`
/// crate, since duplicating a dozen lines is cheaper than a shared-test-
/// utils crate for a two-file need.
fn visible_text_tokens(markdown: &str) -> HashSet<String> {
    unescape_backslashes(markdown)
        .split(|c: char| c.is_whitespace() || "|-:#*_`>\\/.){}".contains(c))
        .filter(|word| !word.is_empty() && !word.chars().all(|c| c.is_ascii_digit()))
        .map(str::to_string)
        .collect()
}

const ESCAPABLE_PUNCTUATION: &str = "!\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~";

fn unescape_backslashes(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    let mut chars = s.chars().peekable();
    while let Some(c) = chars.next() {
        if c == '\\' {
            if let Some(&next) = chars.peek() {
                if ESCAPABLE_PUNCTUATION.contains(next) {
                    out.push(next);
                    chars.next();
                    continue;
                }
            }
        }
        out.push(c);
    }
    out
}

fn fixture_path(name: &str, suffix: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join(format!("tests/golden/{name}{suffix}"))
}

fn check_golden(name: &str) {
    let input = fs::read_to_string(fixture_path(name, ".md"))
        .unwrap_or_else(|e| panic!("reading {name}.md: {e}"));
    let options = RefineOptions::default();
    let actual = refine(&input, &options);

    let snapshot_path = fixture_path(name, ".refined.md");
    match fs::read_to_string(&snapshot_path) {
        Ok(expected) => assert_eq!(
            actual, expected,
            "{name}: refined output drifted from the checked-in snapshot -- \
             if this change is intended, update {name}.refined.md and say why in the commit"
        ),
        Err(_) => panic!(
            "{name}: no snapshot at {snapshot_path:?} -- run refine() once and check in \
             its output as the initial snapshot"
        ),
    }

    let twice = refine(&actual, &options);
    assert_eq!(
        actual, twice,
        "{name}: refine is not idempotent on real renderer output"
    );

    let before = visible_text_tokens(&input);
    let after = visible_text_tokens(&actual);
    assert!(
        before.is_subset(&after),
        "{name}: lost tokens from real renderer output: {:?}",
        before.difference(&after).collect::<Vec<_>>()
    );
}

#[test]
fn unpdf_sample_matches_snapshot() {
    check_golden("unpdf-sample");
}

#[test]
fn undoc_sample_matches_snapshot() {
    check_golden("undoc-sample");
}

#[test]
fn unhwp_sample_matches_snapshot() {
    check_golden("unhwp-sample");
}
